<?php
/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * @author Jim Berry ("solotandem", http://drupal.org/user/240748)
 */
 
 
/**
 * Implementation of hook_menu().
 * 
 */
function cmis_library_menu() {
  $items = array();
  
  $items['admin/settings/cmis/library'] = array(
    'type' => MENU_CALLBACK,
    'title' => t('CMIS Library checker'),
    'page callback' => 'cmis_library_lib_check', 
    'access callback' => 'user_access', 
    'access arguments' => array('access cmis'),
  );  
    
  return $items;
}

function cmis_library_lib_check() {
  $library = libraries_detect('cmislib');
  //debug($library);
  if ($library['installed']){
    return t('PHP CMIS Library detected - everything is good!');
  }else{
    $string = '<h1 class="error">'.t('PHP CMIS Library not detected').'</h1>';
    $string .= '<p>'.t('Please download the PHP CMIS Library from apache chemistry (https://svn.apache.org/repos/asf/chemistry/phpclient/trunk)').'</p>';
    $string .= "<p>".t('Please check you libraries directory, the CMIS lib should be located at'). "<site>/libraries/cmislib/trunk/lib/cmis_repository_wrapper.php".t(' or equivalent')."</p>";
	return $string;
  }
  //return $library;
}


/** 
 * Short-circuit the version argument. 
 */ 
function short_circuit_version() { 
  return TRUE; 
} 

/**
 * Implements hook_libraries_info().
 */
function cmis_library_libraries_info() {
  $libraries = array(); 
  $libraries['cmislib'] = array(
    'name' => 'CMIS Library',
    'vendor url' => 'http://chemistry.apache.org/php/phpclient.html',
    'download url' => 'https://svn.apache.org/repos/asf/chemistry/phpclient/trunk',
    'version callback' => 'short_circuit_version',
    'path' => 'trunk/lib',
    'files' => array(
      'php' => array('cmis_repository_wrapper.php'),
    ),
  );
  return $libraries;
}

 /*   'download url' => 'http://drupal.org/project/grammar_parser',
    'version arguments' => array(
      'file'    => 'CHANGELOG.txt',
      'pattern' => '/pgp \(grammar parser\) (\d+\.x-\d+\.x)/',
    ),*/