<?php

/**
 * Implementation of hook_cmis_invoke($url, $properties, $settings)
 *
 * $conf example:
 * $conf['cmis_repositories'] = array(
 *   'default' => array(
 *     'user' => 'admin',
 *     'password' => 'admin',
 *     'label' => 'local cmis repo',
 *     'url' => 'http://127.0.0.1:8080/cmis',
 *     'transport' => 'cmis_headerswing',
 *     'headerswing_headers' => array(
 *       'HTTP_HOST' => 'FRONTENT_HOST',
 *       'HTTP_HOST' => 'FRONTENT_HOST_AGAIN',
 *       'HTTP_USER' => 'FRONTENT_USER',
 *       'PHP_AUTH_USER' => 'FRONTENT_USER'
 *       'PHP_AUTH_DIGEST' => 'FRONTEND_AUTH'
 *     )
 *   ),
 *  ...
 * );
 *
 */
function cmis_headerswing_cmis_invoke($url, $properties, $settings) {
  if (array_key_exists('headerswing_headers', $settings)) {
    if (!array_key_exists('headers', $properties)) {
      $properties['headers'] = array();
    }

    foreach($settings['headerswing_headers'] as $header_src => $header_dest) {
      if(array_key_exists($header_src, $_SERVER)) {
        $properties['headers'][$header_dest] = $_SERVER[$header_src];
      }
    }
  }
  return cmis_common_cmis_invoke($url, $properties, $settings);
}
